-- VEYORA + Supabase database setup
-- Run this entire script in Supabase SQL Editor.
-- Then create the admin Auth user:
-- Email: mubashir098@gmail.com
-- Password: 894375
-- IMPORTANT: the password belongs in Supabase Auth, NOT in the website code.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null default '',
  phone text default '',
  location text default '',
  role text not null default 'customer' check (role in ('customer','admin')),
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    case when lower(new.email) = lower('mubashir098@gmail.com') then 'admin' else 'customer' end
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null default 'Smart Gadgets',
  price numeric(12,2) not null check (price >= 0),
  old_price numeric(12,2) not null default 0 check (old_price >= 0),
  discount numeric(5,2) not null default 0 check (discount >= 0),
  icon text default '📦',
  image_url text,
  description text,
  stock integer not null default 0 check (stock >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.cart_items (
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  quantity integer not null default 1 check (quantity > 0),
  created_at timestamptz not null default now(),
  primary key (user_id, product_id)
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  total numeric(12,2) not null check (total >= 0),
  status text not null default 'PENDING'
    check (status in ('PENDING','DISPATCHED','IN TRANSIT','DELIVERED','CANCELLED')),
  delivery_location text default '',
  customer_name text not null default '',
  customer_phone text not null default '',
  delivery_address text not null default '',
  payment_method text not null default 'Cash on Delivery',
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12,2) not null check (unit_price >= 0),
  icon text default '📦'
);

-- Enable RLS on every exposed table.
alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.cart_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- Profiles
drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles
for select to authenticated
using ((select auth.uid()) = id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own" on public.profiles
for insert to authenticated
with check ((select auth.uid()) = id);

drop policy if exists "profiles_update_own_nonrole" on public.profiles;
drop policy if exists "profiles_update_own_safe_role" on public.profiles;
create policy "profiles_update_own_safe_role" on public.profiles
for update to authenticated
using ((select auth.uid()) = id)
with check (
  (select auth.uid()) = id
  and (role = 'customer' or lower((select auth.jwt()->>'email')) = lower('mubashir098@gmail.com'))
);

-- Products: public read; admin write.
drop policy if exists "products_public_read" on public.products;
create policy "products_public_read" on public.products
for select to anon, authenticated using (true);

drop policy if exists "products_admin_insert" on public.products;
create policy "products_admin_insert" on public.products
for insert to authenticated
with check (exists (select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

drop policy if exists "products_admin_update" on public.products;
create policy "products_admin_update" on public.products
for update to authenticated
using (exists (select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'))
with check (exists (select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

drop policy if exists "products_admin_delete" on public.products;
create policy "products_admin_delete" on public.products
for delete to authenticated
using (exists (select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

-- Cart: owner only.
drop policy if exists "cart_owner_all" on public.cart_items;
create policy "cart_owner_all" on public.cart_items
for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

-- Orders: customer can create/read own; admin can read/update all.
drop policy if exists "orders_customer_select" on public.orders;
create policy "orders_customer_select" on public.orders
for select to authenticated
using ((select auth.uid()) = user_id or exists (select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

drop policy if exists "orders_customer_insert" on public.orders;
create policy "orders_customer_insert" on public.orders
for insert to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "orders_admin_update" on public.orders;
create policy "orders_admin_update" on public.orders
for update to authenticated
using (exists (select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'))
with check (exists (select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

-- Order items: customers can read their order items; customers can insert items into their own order;
-- admins can read/update as needed.
drop policy if exists "order_items_read" on public.order_items;
create policy "order_items_read" on public.order_items
for select to authenticated
using (
  exists (
    select 1 from public.orders o
    where o.id=order_id
      and (o.user_id=auth.uid()
           or exists (select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'))
  )
);

drop policy if exists "order_items_insert_own" on public.order_items;
create policy "order_items_insert_own" on public.order_items
for insert to authenticated
with check (
  exists (
    select 1 from public.orders o
    where o.id=order_id and o.user_id=auth.uid()
  )
);

-- Grants: least privilege for browser access.
grant select on public.products to anon, authenticated;
grant select, insert, update, delete on public.profiles to authenticated;
grant select, insert, update, delete on public.cart_items to authenticated;
grant select, insert, update on public.orders to authenticated;
grant select, insert on public.order_items to authenticated;

-- Seed products.
insert into public.products (name,category,price,old_price,discount,icon,stock)
select * from (values
 ('Smart LED TV 43"','Televisions & Displays',24999,29999,17,'📺',20),
 ('Portable Bluetooth Speaker','Smart Gadgets',1499,1999,25,'🔊',50),
 ('Rechargeable Table Fan','Home & Kitchen',899,1199,25,'🌀',30),
 ('Microfiber Ceiling Fan Cleaner','Home & Kitchen',499,699,29,'🧹',50),
 ('Digital Smart Watch','Smart Gadgets',1299,1799,28,'⌚',40),
 ('Wireless Earbuds','Smart Gadgets',999,1499,33,'🎧',60),
 ('Electric Trimmer','Beauty & Health',699,999,30,'🪒',35),
 ('USB Rechargeable Torch','Smart Gadgets',349,499,30,'🔦',80)
) as v(name,category,price,old_price,discount,icon,stock)
where not exists (select 1 from public.products);

-- After creating the admin Auth account, the trigger will assign role='admin'
-- because the email is mubashir098@gmail.com.
